[package]
name = "r2engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uom = "0.35.0"
nom = "7"
dimensioned = "0.8.0"
